version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: musteri_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: musteri_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d musteri_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - musteri_network

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: musteri_api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:123456@postgres:5432/musteri_db
    restart: unless-stopped
    networks:
      - musteri_network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: musteri_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    restart: unless-stopped
    networks:
      - musteri_network

volumes:
  postgres_data:

networks:
  musteri_network:
    driver: bridge
